### PR TITLE
Bump to v0.6.0

### PR DESCRIPTION
**Pull request by vlopes11**

### CODE REVIEW

**Review by Voxelot — APPROVED** [review]

**Review by adlerjohn — APPROVED** [review]

**Review by adlerjohn — CHANGES_REQUESTED** [review]
Actually, can we wait until https://github.com/FuelLabs/fuel-specs/pull/353 is in `fuel-asm`? The other chain of breaks to e.g. the transaction format will mess up the standard library.

#80

**Review by Voxelot — CHANGES_REQUESTED** [review]
blocked on instruction to get parts of a tx

**Comment by vlopes11** [comment]
Blocked on https://github.com/FuelLabs/fuel-asm/pull/81

**Comment by adlerjohn** [comment]
Can we also get #79 in for this release?

**Review by adlerjohn — APPROVED** [review]

**Review by Dentosal — APPROVED** [review]
LGTM, now includes CIMV and CTVM opcode removal as well

**Pull request merged**
